[package]
name = "libtls"
version = "3.0.2"
authors = ["Reyk Floeter <contact@reykfloeter.com>"]
edition = "2018"

[dependencies]
libtls-sys = { path = "../libtls-sys" }

[dev-dependencies]
rand = "*"
