[package]
name = "tokio-libtls"
version = "1.0.0-alpha7"
authors = ["Reyk Floeter <contact@reykfloeter.com>"]
edition = "2018"
license = "ISC"
readme = "README.md"
description = "Tokio bindings for LibreSSL's libtls."
repository = "https://github.com/reyk/rust-libtls"
categories = ["asynchronous", "cryptography", "network-programming"]
keywords = ["tokio", "tls", "ssl", "libressl", "openbsd"]
documentation = "https://reyk.github.io/rust-libtls/libtls/"

[badges]
travis-ci = { repository = "reyk/rust-libtls", branch = "master" }

[dependencies]
libtls = { path = "../libtls", version = "1.0.0-alpha7" }
futures = "0.1.29"
mio = "0.6.19"
tokio-io = "0.1.12"
tokio-reactor = "0.1.10"
tokio-tcp = "0.1.3"

[dev-dependencies]
tokio = "0.1.22"
